name: iaminator

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: iam-lint
      - uses: actions/checkout@v2
        uses: xen0l/iam-lint@v1
        with:
          path: 'policies'